# This is a basic workflow to help you get started with Actions

name: 'CI-publish'

# Controls when the workflow will run
on:
  release:
    types: [ created ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    runs-on: ubuntu-latest
#    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Publish app
        run: ./gradlew --stacktrace deploy
        env:
          CONTAINER_REGISTRY_PASS: ${{ secrets.CONTAINER_REGISTRY_PASS }}
          CONTAINER_REGISTRY_USER: ${{ secrets.CONTAINER_REGISTRY_USER }}
          CONTAINER_REGISTRY_HOST: ${{ vars.CONTAINER_REGISTRY_HOST }}
          CONTAINER_REGISTRY_PREF: ${{ vars.CONTAINER_REGISTRY_PREF }}
          PROJECT_VERSION: ${{ github.event.release.tag_name }}
